RECORD_TYPE_POMODORO = 0
RECORD_TYPE_SHORT = 1
RECORD_TYPE_LONG = 2
RECORD_TYPES = (
    (RECORD_TYPE_POMODORO, "Pomodoro"),
    (RECORD_TYPE_SHORT, "Short Break"),
    (RECORD_TYPE_LONG, "Long Break"),
)
